version: '2.2'

services:

  postgres_test:
    image: postgres:11.4
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

